apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend
  - frontend
namespace: study-app
namePrefix: prod-
images:
  - name: ghcr.io/dylunabadylu/study-app-api
    newTag: backend-v0.3.4
  - name: ghcr.io/dylunabadylu/study-app-web
    newTag: frontend-v0.1.2
